INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Albánie?', 'Tirana');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Andorry?', 'Andorra la Vella');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Arménie?', 'Jerevan');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Ázerbájdžánu?', 'Baku');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Běloruska?', 'Minsk');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Belgie?', 'Brusel');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Bosny a Hercegoviny?', 'Sarajevo');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Bulharska?', 'Sofie');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Chorvatska?', 'Záhřeb');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Kypru?', 'Nikósie');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Česka?', 'Praha');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Dánska?', 'Kodaň');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Estonska?', 'Tallinn');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Finska?', 'Helsinky');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Francie?', 'Paříž');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Gruzie?', 'Tbilisi');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Německa?', 'Berlín');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Řecka?', 'Atény');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Maďarska?', 'Budapešť');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Islandu?', 'Reykjavík');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Irska?', 'Dublin');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Itálie?', 'Řím');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Kazachstánu?', 'Astana');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Kosova?', 'Priština');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Lotyšska?', 'Riga');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Lichtenštejnska?', 'Vaduz');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Litvy?', 'Vilnius');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Lucemburska?', 'Lucemburk');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Malty?', 'Valletta');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Moldavska?', 'Kišiněv');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Monaka?', 'Monako');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Černé Hory?', 'Podgorica');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Nizozemska?', 'Amsterdam');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Severní Makedonie?', 'Skopje');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Norska?', 'Oslo');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Polska?', 'Varšava');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Portugalska?', 'Lisabon');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Rumunska?', 'Bukurešť');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Ruska?', 'Moskva');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město San Marina?', 'San Marino');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Srbska?', 'Bělehrad');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Slovenska?', 'Bratislava');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Slovinska?', 'Lublaň');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Španělska?', 'Madrid');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Švédska?', 'Stockholm');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Švýcarska?', 'Bern');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Turecka?', 'Ankara');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Ukrajiny?', 'Kyjev');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Vatikánu?', 'Vatikán');
INSERT INTO questions (quiz, question, correct) VALUES ('EU_CAPITALS', 'Jaké je hlavní město Velké Británie?', 'Londýn');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Afghánistánu?','Kábul');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Arménie?','Jerevan');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Ázerbájdžánu?','Baku');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Bahrajnu?','Manáma');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Bangladéše?','Dháka');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Bhútánu?','Thimphu');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Bruneje?','Bandar Seri Begawan');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Kambodže?','Phnompenh');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Číny?','Peking');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Gruzie?','Tbilisi');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Indie?','Nové Dillí');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Indonésie?','Jakarta');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Íránu?','Teherán');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Iráku?','Bagdád');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Izraele?','Jeruzalém');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Japonska?','Tokio');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Jordánska?','Ammán');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Kazachstánu?','Astana');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Kuvajtu?','Kuvajt');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Kyrgyzstánu?','Biškek');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Laosu?','Vientiane');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Libanonu?','Bejrút');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Malajsie?','Kuala Lumpur');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Malediv?','Male');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Mongolska?','Ulánbátar');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Myanmaru?','Naypyidaw');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Nepálu?','Káthmándú');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Severní Koreje?','Pchjongjang');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Ománu?','Maskat');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Pákistánu?','Islámábád');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Filipín?','Manila');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Kataru?','Dauhá');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Saúdské Arábie?','Rijád');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Singapuru?','Singapur');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Jižní Koreje?','Soul');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Srí Lanky?','Šrí Džajavardanapura Kotte');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Sýrie?','Damašek');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Tádžikistánu?','Dušanbe');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Thajska?','Bangkok');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Východního Timoru?','Dili');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Turecka?','Ankara');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Turkmenistánu?','Ašchabad');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Spojených arabských emirátů?','Abú Zabí');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Uzbekistánu?','Taškent');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Vietnamu?','Hanoj');
INSERT INTO questions (quiz, question, correct) VALUES ('ASIA_CAPITALS','Jaké je hlavní město Jemenu?','Saná');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Alžírska?','Alžír');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Angoly?','Luanda');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Beninu?','Porto-Novo');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Botswany?','Gaborone');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Burkiny Faso?','Ouagadougou');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Burundi?','Gitega');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Kapverd?','Praia');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Kamerunu?','Yaoundé');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Středoafrické republiky?','Bangui');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Čadu?','N Djamena');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Komor?','Moroni');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Konga?','Brazzaville');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město DR Kongo?','Kinshasa');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Pobřeží slonoviny?','Yamoussoukro');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Džibutska?','Džibuti');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Egypta?','Káhira');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Rovníkové Guiney?','Malabo');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Eritrey?','Asmara');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Eswatini?','Mbabane');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Etiopie?','Addis Abeba');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Gabonu?','Libreville');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Gambie?','Banjul');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Ghany?','Accra');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Guiney?','Conakry');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Guiney-Bissau?','Bissau');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Keni?','Nairobi');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Lesotha?','Maseru');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Libérie?','Monrovia');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Libye?','Tripolis');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Madagaskaru?','Antananarivo');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Malawi?','Lilongwe');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Mali?','Bamako');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Mauritánie?','Nouakchott');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Mauricia?','Port Louis');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Maroka?','Rabat');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Mosambiku?','Maputo');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Namibie?','Windhoek');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Nigeru?','Niamey');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Nigérie?','Abuja');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Rwandy?','Kigali');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Svatého Tomáše a Princova ostrova?','São Tomé');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Senegalu?','Dakar');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Seychel?','Victoria');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Sierry Leone?','Freetown');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Somálska?','Mogadišo');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Jihoafrické republiky?','Pretoria');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Jižního Súdánu?','Juba');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Súdánu?','Chartúm');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Tanzanie?','Dodoma');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Toga?','Lomé');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Tuniska?','Tunis');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Ugandy?','Kampala');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Zambie?','Lusaka');
INSERT INTO questions (quiz, question, correct) VALUES ('AFRICA_CAPITALS','Jaké je hlavní město Zimbabwe?','Harare');
INSERT INTO questions (quiz, question, correct) VALUES ('NORTH_AMERICA_CAPITALS','Jaké je hlavní město Antiguy a Barbudy?','Saint John''s');
INSERT INTO questions (quiz, question, correct) VALUES ('NORTH_AMERICA_CAPITALS','Jaké je hlavní město Baham?','Nassau');
INSERT INTO questions (quiz, question, correct) VALUES ('NORTH_AMERICA_CAPITALS','Jaké je hlavní město Barbadosu?','Bridgetown');
INSERT INTO questions (quiz, question, correct) VALUES ('NORTH_AMERICA_CAPITALS','Jaké je hlavní město Belize?','Belmopan');
INSERT INTO questions (quiz, question, correct) VALUES ('NORTH_AMERICA_CAPITALS','Jaké je hlavní město Kanady?','Ottawa');
INSERT INTO questions (quiz, question, correct) VALUES ('NORTH_AMERICA_CAPITALS','Jaké je hlavní město Kostariky?','San José');
INSERT INTO questions (quiz, question, correct) VALUES ('NORTH_AMERICA_CAPITALS','Jaké je hlavní město Kuby?','Havana');
INSERT INTO questions (quiz, question, correct) VALUES ('NORTH_AMERICA_CAPITALS','Jaké je hlavní město Dominiky?','Roseau');
INSERT INTO questions (quiz, question, correct) VALUES ('NORTH_AMERICA_CAPITALS','Jaké je hlavní město Dominikánské republiky?','Santo Domingo');
INSERT INTO questions (quiz, question, correct) VALUES ('NORTH_AMERICA_CAPITALS','Jaké je hlavní město Salvadoru?','San Salvador');
INSERT INTO questions (quiz, question, correct) VALUES ('NORTH_AMERICA_CAPITALS','Jaké je hlavní město Grenady?','Saint George''s');
INSERT INTO questions (quiz, question, correct) VALUES ('NORTH_AMERICA_CAPITALS','Jaké je hlavní město Guatemaly?','Guatemala City');
INSERT INTO questions (quiz, question, correct) VALUES ('NORTH_AMERICA_CAPITALS','Jaké je hlavní město Haiti?','Port-au-Prince');
INSERT INTO questions (quiz, question, correct) VALUES ('NORTH_AMERICA_CAPITALS','Jaké je hlavní město Hondurasu?','Tegucigalpa');
INSERT INTO questions (quiz, question, correct) VALUES ('NORTH_AMERICA_CAPITALS','Jaké je hlavní město Jamajky?','Kingston');
INSERT INTO questions (quiz, question, correct) VALUES ('NORTH_AMERICA_CAPITALS','Jaké je hlavní město Mexika?','Ciudad de México');
INSERT INTO questions (quiz, question, correct) VALUES ('NORTH_AMERICA_CAPITALS','Jaké je hlavní město Nikaraguy?','Managua');
INSERT INTO questions (quiz, question, correct) VALUES ('NORTH_AMERICA_CAPITALS','Jaké je hlavní město Panamy?','Panama City');
INSERT INTO questions (quiz, question, correct) VALUES ('NORTH_AMERICA_CAPITALS','Jaké je hlavní město Svaté Lucie?','Castries');
INSERT INTO questions (quiz, question, correct) VALUES ('NORTH_AMERICA_CAPITALS','Jaké je hlavní město Svatého Kryštofa a Nevisu?','Basseterre');
INSERT INTO questions (quiz, question, correct) VALUES ('NORTH_AMERICA_CAPITALS','Jaké je hlavní město Svatého Vincence a Grenadin?','Kingstown');
INSERT INTO questions (quiz, question, correct) VALUES ('NORTH_AMERICA_CAPITALS','Jaké je hlavní město Trinidadu a Tobaga?','Port of Spain');
INSERT INTO questions (quiz, question, correct) VALUES ('NORTH_AMERICA_CAPITALS','Jaké je hlavní město USA?','Washington, D.C.');
INSERT INTO questions (quiz, question, correct) VALUES ('SOUTH_AMERICA_CAPITALS','Jaké je hlavní město Argentiny?','Buenos Aires');
INSERT INTO questions (quiz, question, correct) VALUES ('SOUTH_AMERICA_CAPITALS','Jaké je hlavní město Bolívie?','Sucre');
INSERT INTO questions (quiz, question, correct) VALUES ('SOUTH_AMERICA_CAPITALS','Jaké je hlavní město Brazílie?','Brasília');
INSERT INTO questions (quiz, question, correct) VALUES ('SOUTH_AMERICA_CAPITALS','Jaké je hlavní město Chile?','Santiago de Chile');
INSERT INTO questions (quiz, question, correct) VALUES ('SOUTH_AMERICA_CAPITALS','Jaké je hlavní město Kolumbie?','Bogotá');
INSERT INTO questions (quiz, question, correct) VALUES ('SOUTH_AMERICA_CAPITALS','Jaké je hlavní město Ekvádoru?','Quito');
INSERT INTO questions (quiz, question, correct) VALUES ('SOUTH_AMERICA_CAPITALS','Jaké je hlavní město Guyany?','Georgetown');
INSERT INTO questions (quiz, question, correct) VALUES ('SOUTH_AMERICA_CAPITALS','Jaké je hlavní město Paraguaye?','Asunción');
INSERT INTO questions (quiz, question, correct) VALUES ('SOUTH_AMERICA_CAPITALS','Jaké je hlavní město Peru?','Lima');
INSERT INTO questions (quiz, question, correct) VALUES ('SOUTH_AMERICA_CAPITALS','Jaké je hlavní město Surinamu?','Paramaribo');
INSERT INTO questions (quiz, question, correct) VALUES ('SOUTH_AMERICA_CAPITALS','Jaké je hlavní město Uruguaye?','Montevideo');
INSERT INTO questions (quiz, question, correct) VALUES ('SOUTH_AMERICA_CAPITALS','Jaké je hlavní město Venezuely?','Caracas');
INSERT INTO questions (quiz, question, correct) VALUES ('OCEANIA_CAPITALS','Jaké je hlavní město Austrálie?','Canberra');
INSERT INTO questions (quiz, question, correct) VALUES ('OCEANIA_CAPITALS','Jaké je hlavní město Fidži?','Suva');
INSERT INTO questions (quiz, question, correct) VALUES ('OCEANIA_CAPITALS','Jaké je hlavní město Kiribati?','Tarawa');
INSERT INTO questions (quiz, question, correct) VALUES ('OCEANIA_CAPITALS','Jaké je hlavní město Marshallových ostrovů?','Majuro');
INSERT INTO questions (quiz, question, correct) VALUES ('OCEANIA_CAPITALS','Jaké je hlavní město Mikronésie?','Palikir');
INSERT INTO questions (quiz, question, correct) VALUES ('OCEANIA_CAPITALS','Jaké je hlavní město Nauru?','Yaren (de facto)');
INSERT INTO questions (quiz, question, correct) VALUES ('OCEANIA_CAPITALS','Jaké je hlavní město Nového Zélandu?','Wellington');
INSERT INTO questions (quiz, question, correct) VALUES ('OCEANIA_CAPITALS','Jaké je hlavní město Palau?','Ngerulmud');
INSERT INTO questions (quiz, question, correct) VALUES ('OCEANIA_CAPITALS','Jaké je hlavní město Papuy-Nové Guiney?','Port Moresby');
INSERT INTO questions (quiz, question, correct) VALUES ('OCEANIA_CAPITALS','Jaké je hlavní město Samoy?','Apia');
INSERT INTO questions (quiz, question, correct) VALUES ('OCEANIA_CAPITALS','Jaké je hlavní město Šalomounových ostrovů?','Honiara');
INSERT INTO questions (quiz, question, correct) VALUES ('OCEANIA_CAPITALS','Jaké je hlavní město Tongy?','Nuku''alofa');
INSERT INTO questions (quiz, question, correct) VALUES ('OCEANIA_CAPITALS','Jaké je hlavní město Tuvalu?','Funafuti');
INSERT INTO questions (quiz, question, correct) VALUES ('OCEANIA_CAPITALS','Jaké je hlavní město Vanuatu?','Port Vila');
